baseURL = "http://lasasurveyor.com/"
languageCode = "en-us"
title = "LASA Surveyor"

[params]
isSurveyUnlocked = true
surveyURL = "https://forms.gle/Kggs2KQ6Yw3dUEws7"

[menus]
[[menus.main]]
name = "Home"
pageRef = "/"
weight = 1

[[menus.main]]
name = "About/Contact"
pageRef = "/about/"
weight = 4

[[menus.main]]
name = "Posts"
pageRef = "/posts/"
weight = 3

[[menus.main]]
name = "Survey"
pageRef = "/survey/"
weight = 2
